apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer  # note this is DigitalOcean load balance for the pods
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80  # should be the same in the deployment
  selector:
    app: nginx-deployment
