apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web-deployment
  labels:
    app: django-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-web-deployment
  template:
    metadata:
      labels:
        app: django-web-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: registry.digitalocean.com/made-by-li/django-k8s-web:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: django-k8s-web-prod-env
        env:
        - name: PORT
          value: "8001"
        ports:
        - containerPort: 8002
      imagePullSecrets:
      - name: made-by-li

---

apiVersion: v1
kind: Service
metadata:
  name: django-web-service
spec:
  type: LoadBalancer  # note this is DigitalOcean load balance for the pods
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002  # should be the same in the deployment
  selector:
    app: django-web-deployment
